apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: angular-app
  namespace: backend
spec:
  hosts:
    - "*"
  gateways:
    - api-gateway
  http:
    - match:
        - uri:
            prefix: "/app"
      route:
        - destination:
            host: angular-app.backend.svc.cluster.local
            port:
              number: 80
