apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth-secret
  namespace: backend
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA== #root echo -n 'root' |  base64
  MONGO_INITDB_ROOT_PASSWORD: cm9vdA== #root echo -n 'root' |  base64