apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: backend
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "aab++112"
  POSTGRES_DB: "keycloak"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: backend
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
