name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Replace with your target branch name
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM64)
        if: matrix.arch == 'arm64'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and Push Docker image with Kaniko
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v /kaniko/.docker/config.json:/kaniko/.docker/config.json \
            gcr.io/kaniko-project/executor:latest \
            --dockerfile /workspace/auth-service/Dockerfile \
            --context /workspace/auth-service \
            --destination ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
      
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}