#name: "Merge - Angular"
#
#on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main
#      - develop
#
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true
#
#jobs:
#  build:
#    if: github.event.pull_request.merged == true
#    name: "Build"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20.x'
#      - name: Confirm Node.js version
#        run: node -v
#
#      - name: Cache node modules
#        id: cache-npm
#        uses: actions/cache@v4
#        env:
#          cache-name: cache-node-modules
#        with:
#            # npm cache files are stored in `~/.npm` on Linux/macOS
#          path: ~/.npm
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#
#      - name: Install dependencies
#        working-directory: frontend
#        run: npm install
#
#      - name: Build
#        working-directory: frontend
#        run: npm run build
#
#  semantic-versioning:
#    if: github.event.pull_request.merged == true
#    name: Semantic Versioning
#    runs-on: ubuntu-latest
#    outputs:
#      image-tag: ${{ steps.get-tag.outputs.new_tag }}
#    permissions:
#      contents: write
#    steps:
#    - uses: actions/checkout@v4
#      with:
#        fetch-depth: '0'
#    - name: Get tag
#      id: get-tag
#      uses: anothrNick/github-tag-action@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        WITH_V: false
#        MAJOR_STRING_TOKEN: breaking-change
#        MINOR_STRING_TOKEN: feat
#        PATCH_STRING_TOKEN: fix
#
#  push-to-registry:
#    name: Push Docker image to Docker Hub
#    needs: [build, semantic-versioning]
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Cache node modules
#        id: cache-npm
#        uses: actions/cache@v3
#        env:
#          cache-name: cache-node-modules
#        with:
#            # npm cache files are stored in `~/.npm` on Linux/macOS
#          path: ~/.npm
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@v5
#        with:
#          context: ./frontend
#          file: ./frontend/Dockerfile
#          push: true
#          tags: |
#            ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}:${{needs.semantic-versioning.outputs.image-tag}}
#            ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}:latest