name: "Merge - Auth service"

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
         go-version-file: 'auth-service/go.mod'
         check-latest: true
         cache-dependency-path: |
           auth-service/go.mod
      
      - name: Clear Go modules cache directory
        run: sudo rm -rf ~/go/pkg/mod
   
      - name: Cache go modules
        uses: actions/cache@v4
        with:
         path: |
           ~/.cache/go-build
           ~/go/pkg/mod
         key: ${{ runner.os }}-go-${{ hashFiles('**/auth-service/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-go-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}:${{needs.semantic-versioning.outputs.image-tag}}
            ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}:latest