name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Replace with your target branch name
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM64)
        if: matrix.arch == 'arm64'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Kaniko build amd64
        if: matrix.arch == 'linux/amd64'
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: latest
          path: ./auth-service
          build_file: Dockerfile
          cache: true

      - name: Kaniko build arm64
        if: matrix.arch == 'linux/arm64'
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: latest
          path: ./auth-service
          build_file: Dockerfile
          cache: true

      - name: Push manifest (combine architectures)
        if: always()
        run: docker manifest create ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest-amd64 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest-arm64 && docker manifest push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest