name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Replace with your target branch name
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM64)
        if: matrix.arch == 'arm64'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set working directory to auth-service
        run: cd auth-service
      - name: List workspace contents
        run: ls -R  
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_latest: true
          tag: 1.2.2
          cache: true
          cache_registry: ${{ secrets.DOCKER_USERNAME }}/cache