name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Replace with your target branch name
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM64)
        if: matrix.arch == 'arm64'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - name: Get Docker Metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to Docker Hub with Kaniko
        id: kaniko
        uses: int128/kaniko-action@v1
        with:
          push: true
          context: ./auth-service
          tags: 1.2.2
          cache: true
          cache-repository: docker.io/${{ github.repository }}/cache
        
        env:
          DOCKER_CONFIG: /kaniko/.docker/