name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Replace with your target branch name
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM64)
        uses: docker/setup-qemu-action@v2 # Use the official action for QEMU setup
        with:
          platforms: linux/arm64

      - name: Kaniko build amd64
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: latest
          path: ./auth-service
          build_file: Dockerfile
          cache: true
          cache_registry: ${{ secrets.DOCKER_USERNAME }}/cache
          extra_args: |
            --custom-platform=linux/arm64
          
 