name: "Pull Request - Auth service"
on:
 workflow_dispatch:
 pull_request:
   types: [opened, reopened, synchronize]
   paths:
     - 'auth-service/**'
     - '.github/workflows/**'

concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true

jobs:
 build:
   name: "Build"
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Setup Go
       uses: actions/setup-go@v5
       with:
        go-version-file: 'auth-service/go.mod'
        check-latest: true
  
     - uses: actions/cache@v3
       with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

     - name: Install dependencies
       working-directory: auth-service
       run: go get .

     - name: Build
       working-directory: auth-service
       run: go build -v ./...

     - name: Test
       working-directory: auth-service
       run: go test -v ./...